### ISSUE TITLE
npm run bulid 报错

### ISSUE THREAD

**Issue by penghuizhang** [jaxQin/mpvue-cnode#11]
![tim 20190224194724](https://user-images.githubusercontent.com/17181083/53298746-110a7700-386d-11e9-8369-ec00ba4688ab.png)

**Comment by ruochuan12** [comment]
这是因为依赖安装不对。可以锁定依赖版本。另外建议项目作者修复该问题。
参考官方ISSUE [项目删除包从新下载 项目能启动 但是报错 事件失效](https://github.com/Meituan-Dianping/mpvue/issues/1384)
解决方案。
>
>1. 升级最新的mpvue2.0。 升级指南: https://github.com/Meituan-Dianping/mpvue/releases/tag/2.0.0
>2. 升级2.0会增加头条、百度、支付宝小程序的支持，不想升级的同学，可以对以下依赖进行版本锁定，即可， 亲测可用，当然不升旧bug则不能得到解决，风险自行承担。
```package.json
"mpvue": "1.0.18",
"mpvue-loader": "1.1.4",  
"mpvue-template-compiler": "1.0.18"
```
