### ISSUE TITLE
构建时报错：(node:4396) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 20): Error: No parser and no file path given, couldn't infer a parser. \ building for production...

### ISSUE THREAD

**Issue by aasailan** [jaxQin/mpvue-cnode#2]
如题，在clone项目，并且npm install之后，运行npm run dev或者npm run build。都会报错，报错截图如下：
![image](https://user-images.githubusercontent.com/12505615/40636854-16b3f3a2-6334-11e8-9869-0899839c69da.png)

**Comment by 6201** [comment]
这个不是项目本身的问题，你看一下：https://segmentfault.com/q/1010000015052538?_ea=3789885

**Comment by jaxQin** [comment]
npm install --save-dev prettier@1.12.0  应该是prettier升级了新版的原因导致。所以你这里按照这个 指定版本安装就可以了。
