### ISSUE TITLE
怎样引用原生的组件

### ISSUE THREAD

**Issue by muzi131313** [jaxQin/mpvue-cnode#3]
##RT。我做了如下尝试：
1.在main.js中加了
````
usingComponents: {
            'info': 'components/userInfo/index'
}
````
引用的vue中使用组件并没有被渲染出来
2.或者在router/routes.js中
````
{
        path: '/pages/breakfast/index',
        name: 'BreakfastList',
        config: {
            navigationBarTitleText: '早餐',
            // 这儿添加要用的小程序组件
            usingComponents: {
                'info': '../../components/userInfo/index'
            }
        }
    },
````
这样会报
![image](https://user-images.githubusercontent.com/2398149/41267912-303e1c74-6e30-11e8-8488-b88685011a72.png)
这样的错误。
项目目录如下：
![image](https://user-images.githubusercontent.com/2398149/41268025-cc0c15c0-6e30-11e8-83fe-3633a202acfb.png)
![image](https://user-images.githubusercontent.com/2398149/41268036-df4e3b40-6e30-11e8-961b-bc8e962e47d6.png)

**Comment by jaxQin** [comment]
你好。刚刚我试了下引入iview weapp（原生组件）。引入成功。我说下引入方式：

> 1、给对应页面的mainjs  最下面增加如下代码：是页面对应的mainjs不是最外层mainjs

```
export default {
    config: {
        "usingComponents": {
            "i-button": "../../../static/button/index"
        }
    }
}
```

> 2、把组件copy到static下。

> 3、页面使用  

`<i-button type="primary">这是一个按钮</i-button>`

**Comment by muzi131313** [comment]
👍，确实是这样的问题，原生的组件不应该再被编译，我把组件copy到static下就好了。我使用的是mpvue-entry这个库，避免写重复的main.js。参考 [ithome-lite](https://github.com/F-loat/ithome-lite/tree/web-version)
